### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by slaygirlz**

### CODE REVIEW

**Comment by JonathanTippy** [comment]
The services should start on boot anyway, also the minecraft service is a user service so the command would be
 systemctl --user start minecraft

**Comment by JonathanTippy** [comment]
If you followed the instructions and the services don't start on boot, maybe make an issue.

**Comment by slaygirlz** [comment]
no this is a pull just to make things better

**Comment by slaygirlz** [comment]
ehh no use now

**Pull request closed without merging**
